#!/bin/bash
#
# oracledb - little shell script to autostart your oracle database(s) and listener
#
# chkconfig: 2345 90 90
 
# Source function library.
. /etc/init.d/functions
 
# Source networking configuration.
. /etc/sysconfig/network
 
prog=oracledb
lockfile=/var/lock/subsys/$prog
ORACLE_HOME=/u01/app/oracle/product/12.1.0/db_1
  
start() {
  [ "$NETWORKING" = "no" ] && exit 1
  echo -n "Starting $prog: "
  daemon --user=oracle "$ORACLE_HOME/bin/dbstart $ORACLE_HOME > /dev/null 2>&1"
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch $lockfile
  return $RETVAL
}

stop() {
  echo -n "Stopping $prog: "
  daemon --user=oracle "$ORACLE_HOME/bin/dbshut $ORACLE_HOME > /dev/null 2>&1"
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && rm -f $lockfile
  return $RETVAL
}
    
# See how we were called.
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
stop
start
;;
*)
echo $"Usage: $0 {start|stop|restart}"
exit 2
esac
